version: '2'

services:
  postgres:
    image: 'postgres:10.4-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2.11-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'website'
    build: .
    command: sh start_jobs.sh
    volumes:
      - '.:/nosso_amigo_secreto'
    volumes_from:
      - box

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sh start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/nosso_amigo_secreto'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box



volumes:
  redis:
  postgres:
  box: